# -*- coding: utf-8 -*-
"""LAST_PROJECT_DL_QUANTIZATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HWzk2CsCCBuxSpbf-A2WZQOSOAl9og5i

<B> CNN Stress Detection + Quantization Comparison
**Alur Notebook:**
A. Data Preparation → B. Dataset Restructuring → C. Preprocessing → D. Training → E. Evaluation → F. Quantization → G. Comparison → H. Conclusion
"""

from google.colab import drive
drive.mount('/content/drive')

"""<B> A. DATA PREPARATION

<B> A.1 IMPORT LIBRARY
"""

# A.1 IMPORT LIBRARY

import os, time, copy, shutil, zipfile
import torch
import torch.nn as nn
import torch.optim as optim
import torch.quantization
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from tqdm import tqdm
import pandas as pd
from sklearn.metrics import f1_score, confusion_matrix, classification_report
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Device:', device)

# RANDOM SEED (REPRODUCIBILITY)

import random

SEED = 42

random.seed(SEED)
np.random.seed(SEED)

torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

print(f"Random seed set to {SEED}")

"""<B> A.2 UPLOAD & EXTRACK DATASETS"""

# A.2 UPLOAD & EXTRACT ZIP
zip_path = '/content/clean_dataset.zip'

# Cek file ZIP
if os.path.exists(zip_path):
    file_size = os.path.getsize(zip_path)
    print(f"File '{zip_path}' ditemukan. Ukuran: {file_size} bytes")
else:
    print(f"ERROR: File '{zip_path}' tidak ditemukan. Upload dulu ke Colab!")

# Ekstrak ZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('/content/clean_dataset')
print('Ekstraksi selesai!')

"""<B> A.3 CEK STRUKTUR FOLDER DAN JUMLAH GAMBAR PER KELAS"""

# A.3 CEK STRUKTUR FOLDER

ORIGINAL_DIR = '/content/clean_dataset/images'

print('Struktur Folder & Jumlah Gambar')
for split in sorted(os.listdir(ORIGINAL_DIR)):
    split_path = os.path.join(ORIGINAL_DIR, split)
    if not os.path.isdir(split_path):
        continue
    for label in sorted(os.listdir(split_path)):
        label_path = os.path.join(split_path, label)
        if os.path.isdir(label_path):
            n = len(os.listdir(label_path))
            print(f'  {split}/{label}: {n} gambar')

"""<B> A.4 CEK & HAPUS DUPLIKAT TRAIN - VALIDATION (MENCEGAH DATA LEAKAGE)"""

# A.4 CEK DUPLIKAT TRAIN-VALIDATION
# Kumpulkan semua nama file di train
train_files = set()
train_base = os.path.join(ORIGINAL_DIR, 'train')
val_base   = os.path.join(ORIGINAL_DIR, 'validation')

for cls in os.listdir(train_base):
    cls_path = os.path.join(train_base, cls)
    if os.path.isdir(cls_path):
        for f in os.listdir(cls_path):
            train_files.add(f)

# Cek overlap di validation
overlap_count = 0
for cls in os.listdir(val_base):
    cls_path = os.path.join(val_base, cls)
    if not os.path.isdir(cls_path):
        continue
    for f in os.listdir(cls_path):
        if f in train_files:
            overlap_count += 1
            os.remove(os.path.join(cls_path, f))  # Hapus duplikat dari validation

print(f'Duplikat ditemukan dan dihapus dari validation: {overlap_count} file')
print('Data leakage sudah dicegah.')

# Cek ulang jumlah setelah pembersihan
print('\nJumlah Gambar Setelah Pembersihan Duplikat')
for split in ['train', 'validation']:
    split_path = os.path.join(ORIGINAL_DIR, split)
    if not os.path.isdir(split_path):
        continue
    for label in sorted(os.listdir(split_path)):
        label_path = os.path.join(split_path, label)
        if os.path.isdir(label_path):
            n = len(os.listdir(label_path))
            print(f'  {split}/{label}: {n} gambar')

"""<B> B. DATASET RESTRUCTURING
Menggabungkan 7 kelas ekspresi wajah menjadi 2 kelas: **stress** dan **non_stress**.
"""

# B. PEMBENTUKAN DATASET 2 KELAS
stress_classes     = ['angry', 'fear', 'sad', 'disgust']
non_stress_classes = ['happy', 'neutral', 'surprise']
splits = ['train', 'validation']

NEW_DIR = '/content/clean_dataset_2class'

# Bersihkan folder lama
if os.path.exists(NEW_DIR):
    shutil.rmtree(NEW_DIR)

# Buat folder baru
for split in splits:
    os.makedirs(os.path.join(NEW_DIR, split, 'stress'),     exist_ok=True)
    os.makedirs(os.path.join(NEW_DIR, split, 'non_stress'), exist_ok=True)

# Copy file ke folder baru
for split in splits:
    for cls in stress_classes:
        src = os.path.join(ORIGINAL_DIR, split, cls)
        if os.path.exists(src):
            for f in os.listdir(src):
                shutil.copy(os.path.join(src, f),
                            os.path.join(NEW_DIR, split, 'stress', f))
    for cls in non_stress_classes:
        src = os.path.join(ORIGINAL_DIR, split, cls)
        if os.path.exists(src):
            for f in os.listdir(src):
                shutil.copy(os.path.join(src, f),
                            os.path.join(NEW_DIR, split, 'non_stress', f))

# Verifikasi hasil
print('Dataset 2 Kelas')
for split in splits:
    for cls in ['stress', 'non_stress']:
        p = os.path.join(NEW_DIR, split, cls)
        print(f'  {split}/{cls}: {len(os.listdir(p))} gambar')

# VISUALISASI DISTRIBUSI DATASET 2 KELAS
splits = ["Train", "Validation"]
stress = [13470, 3228]
non_stress = [15351, 3838]

x = np.arange(len(splits))
width = 0.35

plt.figure(figsize=(7, 5))

plt.bar(x - width/2, stress, width, label="Stress")
plt.bar(x + width/2, non_stress, width, label="Non-Stress")

plt.title("Distribusi Dataset")
plt.xlabel("Split Dataset")
plt.ylabel("Jumlah Images")
plt.xticks(x, splits)
plt.legend()
plt.grid(axis="y", alpha=0.3)

plt.tight_layout()
plt.show()

"""<B> C. PREPROCESSING & AUGMENTATION"""

# C. PREPROCESSING + AUGMENTATION
# Augmentasi hanya untuk TRAIN; validation hanya resize + normalize

train_tfms = transforms.Compose([
    transforms.Grayscale(num_output_channels=1),
    transforms.Resize((48, 48)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.RandomAffine(degrees=0, translate=(0.1, 0.1), scale=(0.9, 1.1)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5])
])

val_tfms = transforms.Compose([
    transforms.Grayscale(num_output_channels=1),
    transforms.Resize((48, 48)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5])
])

DATA_DIR  = NEW_DIR
train_dir = os.path.join(DATA_DIR, 'train')
val_dir   = os.path.join(DATA_DIR, 'validation')

train_dataset = datasets.ImageFolder(train_dir, transform=train_tfms)
val_dataset   = datasets.ImageFolder(val_dir,   transform=val_tfms)

generator = torch.Generator()
generator.manual_seed(SEED)

train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True,
    num_workers=2,
    generator=generator
)

val_loader = DataLoader(
    val_dataset,
    batch_size=64,
    shuffle=False,
    num_workers=2,
    generator=generator
)

num_classes = len(train_dataset.classes)
print('Classes     :', train_dataset.classes)
print('Num classes :', num_classes)
print('Train samples:', len(train_dataset))
print('Val samples  :', len(val_dataset))

# VISUALISASI AUGMENTASI
images, labels = next(iter(train_loader))

plt.figure(figsize=(12,6))

for i in range(8):
    img = images[i].squeeze().numpy()
    img = (img * 0.5) + 0.5

    plt.subplot(2,4,i+1)
    plt.imshow(img, cmap='gray')
    plt.axis('off')
    plt.title(train_dataset.classes[labels[i]])

plt.suptitle("Sample Training Images After Augmentation")
plt.tight_layout()
plt.show()

# VISUALISASI DATA AUGMENTATION

from PIL import Image

# Ambil 1 gambar asli dari dataset train
sample_path = train_dataset.samples[0][0]
sample_label = train_dataset.samples[0][1]

# Baca gambar asli
original_image = Image.open(sample_path).convert('L')

# Augmentasi khusus training
augment_transform = transforms.Compose([
    transforms.Resize((48, 48)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(15),
    transforms.RandomAffine(
        degrees=0,
        translate=(0.1, 0.1),
        scale=(0.9, 1.1)
    ),
    transforms.ToTensor()
])

fig, axes = plt.subplots(2, 5, figsize=(15, 6))

fig.suptitle(
    f'Data Augmentation — "{train_dataset.classes[sample_label]}"',
    fontsize=16,
    fontweight='bold'
)

# Gambar asli
axes[0, 0].imshow(original_image, cmap='gray')

axes[0, 0].set_title(
    'Original',
    fontsize=11,
    fontweight='bold',
    color='blue'
)

axes[0, 0].axis('off')

# 9 hasil augmentasi
for i in range(1, 10):

    row = i // 5
    col = i % 5

    augmented = augment_transform(original_image)

    axes[row, col].imshow(
        augmented.squeeze(),
        cmap='gray'
    )

    axes[row, col].set_title(
        f'Aug {i}',
        fontsize=10
    )

    axes[row, col].axis('off')

plt.tight_layout()

plt.show()

"""<B> D. TRAINING MODEL CNN"""

# D.1 DEFINISI MODEL CNN
class EmotionCNNDeepFC(nn.Module):
    def __init__(self, num_classes=2):
        super().__init__()
        self.features = nn.Sequential(
            # Block 1
            nn.Conv2d(1, 64, kernel_size=3, padding=1), nn.BatchNorm2d(64),  nn.ReLU(),
            nn.Conv2d(64, 64, kernel_size=3, padding=1), nn.BatchNorm2d(64), nn.ReLU(),
            nn.MaxPool2d(2), nn.Dropout2d(0.25),
            # Block 2
            nn.Conv2d(64, 128, kernel_size=3, padding=1), nn.BatchNorm2d(128), nn.ReLU(),
            nn.Conv2d(128, 128, kernel_size=3, padding=1), nn.BatchNorm2d(128), nn.ReLU(),
            nn.MaxPool2d(2), nn.Dropout2d(0.25),
            # Block 3
            nn.Conv2d(128, 256, kernel_size=3, padding=1), nn.BatchNorm2d(256), nn.ReLU(),
            nn.Conv2d(256, 256, kernel_size=3, padding=1), nn.BatchNorm2d(256), nn.ReLU(),
            nn.MaxPool2d(2), nn.Dropout2d(0.30),
        )
        # input 48x48 → setelah 3x MaxPool2d → 6x6
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(256 * 6 * 6, 1024), nn.BatchNorm1d(1024), nn.ReLU(), nn.Dropout(0.50),
            nn.Linear(1024, 512),          nn.BatchNorm1d(512),  nn.ReLU(), nn.Dropout(0.40),
            nn.Linear(512, 256),           nn.BatchNorm1d(256),  nn.ReLU(), nn.Dropout(0.30),
            nn.Linear(256, 128),                                  nn.ReLU(), nn.Dropout(0.20),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x

model = EmotionCNNDeepFC(num_classes=num_classes).to(device)
print(model)

from torchsummary import summary

print("\nMODEL SUMMARY")
summary(model, (1, 48, 48))

"""<B> D2. LOSS, OPTIMIZER, SCHEDULER"""

# D.2 LOSS, OPTIMIZER, SCHEDULER
criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
optimizer = optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='max', factor=0.5, patience=3
)

def train_one_epoch(model, loader):
    model.train()
    running_loss, correct, total = 0, 0, 0
    for images, labels in tqdm(loader, leave=False):
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item() * images.size(0)
        _, preds = outputs.max(1)
        correct += preds.eq(labels).sum().item()
        total   += labels.size(0)
    return running_loss / total, correct / total

@torch.no_grad()
def evaluate(model, loader, eval_device=device):
    model.eval()
    running_loss, correct, total = 0, 0, 0
    for images, labels in loader:
        images, labels = images.to(eval_device), labels.to(eval_device)
        outputs = model(images)
        loss = criterion(outputs.float(), labels)
        running_loss += loss.item() * images.size(0)
        _, preds = outputs.max(1)
        correct += preds.eq(labels).sum().item()
        total   += labels.size(0)
    return running_loss / total, correct / total

# D.3 TRAINING + EARLY STOPPING
def train_model(model, epochs=80, patience=10, target_acc=0.90,
                save_path='best_emotion_model.pth'):
    best_acc   = 0
    best_state = copy.deepcopy(model.state_dict())
    wait       = 0
    history    = []

    for epoch in range(1, epochs + 1):
        train_loss, train_acc = train_one_epoch(model, train_loader)
        val_loss,   val_acc   = evaluate(model, val_loader)
        scheduler.step(val_acc)

        history.append({
            'epoch': epoch,
            'train_loss': train_loss,
            'train_acc': train_acc,
            'val_loss': val_loss,
            'val_acc': val_acc,
            'lr': optimizer.param_groups[0]['lr']
        })

        print(f"Epoch {epoch:03d} | Train Acc: {train_acc:.4f} | "
              f"Val Acc: {val_acc:.4f} | Val Loss: {val_loss:.4f}")

        if val_acc > best_acc:
            best_acc   = val_acc
            best_state = copy.deepcopy(model.state_dict())
            torch.save(best_state, save_path)
            wait = 0
        else:
            wait += 1

        if val_acc >= target_acc:
            print(f'Early stopping: val acc sudah mencapai {target_acc*100:.0f}%')
            break
        if wait >= patience:
            print('Early stopping: tidak ada improvement lagi.')
            break

    model.load_state_dict(best_state)
    return model, pd.DataFrame(history), best_acc

model, history_df, best_val_acc = train_model(
    model, epochs=80, patience=10, target_acc=0.90,
    save_path='best_emotion_model.pth'
)
print(f'\nBest Val Acc: {best_val_acc:.4f}')
history_df.tail()

# VISUALISASI FILTER LAYER PERTAMA

# Ambil bobot convolution layer pertama
first_conv_weights = model.features[0].weight.data.cpu()

print(
    f"Shape filter layer pertama: "
    f"{first_conv_weights.shape}"
)

# Visualisasi filter
num_filters = first_conv_weights.shape[0]

fig, axes = plt.subplots(
    4,
    8,
    figsize=(16, 8)
)

fig.suptitle(
    'Filter Layer Pertama CNN',
    fontsize=16,
    fontweight='bold'
)

for i, ax in enumerate(axes.flat):

    if i < num_filters:

        # Ambil kernel filter
        kernel = first_conv_weights[i, 0]

        # Normalisasi visualisasi
        kernel = (
            kernel - kernel.min()
        ) / (
            kernel.max() - kernel.min() + 1e-8
        )

        ax.imshow(
            kernel.numpy(),
            cmap='gray'
        )

        ax.set_title(
            f'Filter {i+1}',
            fontsize=8
        )

    ax.axis('off')

plt.tight_layout()

plt.show()

# VISUALISASI FEATURE MAP CNN

# Ambil 1 sample validation
sample_img, sample_label = val_dataset[0]

sample_input = sample_img.unsqueeze(0).to(device)

model.eval()

feature_maps = {}

x = sample_input

with torch.no_grad():

    for idx, layer in enumerate(model.features):

        x = layer(x)

        # Simpan beberapa feature map penting
        if idx in [0, 3, 6]:

            feature_maps[
                f'Layer {idx}'
            ] = x.cpu()

# Visualisasi gambar asli
img_display = sample_img.squeeze().numpy()

img_display = (
    img_display * 0.5
) + 0.5

# Plot feature maps
for layer_name, fmap in feature_maps.items():

    n_features = min(16, fmap.shape[1])

    fig, axes = plt.subplots(
        2,
        8,
        figsize=(16,5)
    )

    fig.suptitle(
        f'Feature Maps — {layer_name}',
        fontsize=14,
        fontweight='bold'
    )

    for i, ax in enumerate(axes.flat):

        if i < n_features:

            ax.imshow(
                fmap[0, i].numpy(),
                cmap='viridis'
            )

            ax.set_title(
                f'Ch {i+1}',
                fontsize=8
            )

        ax.axis('off')

    plt.tight_layout()

    plt.show()

# Tampilkan gambar asli
plt.figure(figsize=(3,3))

plt.imshow(
    img_display,
    cmap='gray'
)

plt.title(
    f'Original Image\n{class_names[sample_label]}'
)

plt.axis('off')

plt.show()

"""<B> E. EVALUATION - ACCURACY, F1 SCORE & CONFUSION MATRIKS"""

# E.1 PLOT TRAINING HISTORY
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(history_df['epoch'], history_df['train_acc'], label='Train Acc')
axes[0].plot(history_df['epoch'], history_df['val_acc'],   label='Val Acc')
axes[0].set_title('Accuracy per Epoch'); axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Accuracy'); axes[0].legend(); axes[0].grid(True)

axes[1].plot(history_df['epoch'], history_df['train_loss'], label='Train Loss')
axes[1].plot(history_df['epoch'], history_df['val_loss'],   label='Val Loss')
axes[1].set_title('Loss per Epoch'); axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Loss'); axes[1].legend(); axes[1].grid(True)

plt.tight_layout()
plt.show()

# LEARNING RATE SCHEDULE
plt.figure(figsize=(7,4))

plt.plot(history_df['epoch'], history_df['lr'], marker='o')

plt.title('Learning Rate Schedule')
plt.xlabel('Epoch')
plt.ylabel('Learning Rate')
plt.grid(True)

plt.show()

# E.2 F1 SCORE & CONFUSION MATRIX (FP32 baseline)
@torch.no_grad()
def get_predictions(model, loader, eval_device=device):
    model.eval()
    all_preds, all_labels = [], []
    for images, labels in loader:
        images = images.to(eval_device)
        outputs = model(images)
        _, preds = outputs.max(1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.numpy())
    return np.array(all_labels), np.array(all_preds)

y_true, y_pred = get_predictions(model, val_loader)
class_names = train_dataset.classes

print('Classification Report')
print(classification_report(y_true, y_pred, target_names=class_names))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.title('Confusion Matrix — FP32 Baseline')
plt.xlabel('Predicted'); plt.ylabel('Actual')
plt.tight_layout(); plt.show()

from sklearn.metrics import precision_recall_curve, average_precision_score
import matplotlib.pyplot as plt
import numpy as np
import torch

@torch.no_grad()
def get_probs(model, loader, eval_device=device):
    model.eval()
    all_probs, all_labels = [], []
    for images, labels in loader:
        images = images.to(eval_device)
        outputs = model(images)
        probs = torch.softmax(outputs, dim=1)
        # Probabilitas kelas stress
        stress_probs = probs[:, 1].cpu().numpy()
        all_probs.extend(stress_probs)
        all_labels.extend(labels.numpy())
    return np.array(all_labels), np.array(all_probs)

y_true_auc, y_score = get_probs(model, val_loader, eval_device=device)

precision, recall, _ = precision_recall_curve(y_true_auc, y_score)

ap_score = average_precision_score(y_true_auc, y_score)

plt.figure(figsize=(7,6))

plt.plot(
    recall,
    precision,
    linewidth=3,
    label=f'AP = {ap_score:.4f}'
)

plt.xlabel("Recall")
plt.ylabel("Precision")

plt.title("Precision-Recall Curve")

plt.legend()
plt.grid(True)

plt.show()

print(f'Average Precision Score: {ap_score:.4f}')

# CORRECT / WRONG PREDICTION
@torch.no_grad()
def collect_predictions(model, loader, eval_device=device, max_images=12):
    model.eval()
    samples = []
    for images, labels in loader:
        images_device = images.to(eval_device)
        outputs = model(images_device)
        probs = torch.softmax(outputs, dim=1)
        confs, preds = probs.max(1)
        for img, label, pred, conf in zip(images, labels, preds.cpu(), confs.cpu()):
            samples.append({
                'image': img,
                'label': label.item(),
                'pred': pred.item(),
                'confidence': conf.item()
            })
    return samples
samples = collect_predictions(model, val_loader)
wrong_samples = [s for s in samples if s['label'] != s['pred']]
correct_samples = [s for s in samples if s['label'] == s['pred']]
def show_samples(samples, title, n=8):
    plt.figure(figsize=(14, 4))
    for i, sample in enumerate(samples[:n]):
        img = sample['image'].squeeze().numpy()
        img = (img * 0.5) + 0.5
        true_label = class_names[sample['label']]
        pred_label = class_names[sample['pred']]
        conf = sample['confidence']
        plt.subplot(1, n, i + 1)
        plt.imshow(img, cmap='gray')
        plt.axis('off')
        plt.title(f'T: {true_label}\nP: {pred_label}\nC: {conf:.2f}', fontsize=8)
    plt.suptitle(title)
    plt.tight_layout()
    plt.show()
show_samples(correct_samples, 'Correct Predictions', n=8)
show_samples(wrong_samples, 'Wrong Predictions', n=8)

"""<B> F. QUANTIZATION/PRECISION VARIANTS"""

# F.1 UTILITAS UKURAN MODEL
def get_model_size_kb(model, path='temp_model.pth'):
    torch.save(model.state_dict(), path)
    size_kb = os.path.getsize(path) / 1024
    os.remove(path)
    return size_kb

def get_object_size_kb(obj, path='temp_obj.pth'):
    torch.save(obj, path)
    size_kb = os.path.getsize(path) / 1024
    os.remove(path)
    return size_kb

# F.2 FP32 — BASELINE
fp32_device = ( 'cuda'
    if torch.cuda.is_available()
    else 'cpu')

fp32_model = EmotionCNNDeepFC(num_classes=num_classes)

fp32_model.load_state_dict(
    torch.load('best_emotion_model.pth',map_location='cpu')
)

fp32_model.eval().to(fp32_device)
fp32_size = get_model_size_kb(fp32_model)
print(f'FP32 model size: {fp32_size:.2f} KB')
models_to_test = {}

# FP32 GPU
models_to_test['fp32'] = {
    'model': fp32_model,
    'device': fp32_device,
    'size_kb': fp32_size,
    'note': 'Baseline full precision on GPU'
}

# FP32 CPU
models_to_test['fp32_cpu'] = {
    'model': fp32_model.cpu(),
    'device': 'cpu',
    'size_kb': fp32_size,
    'note': 'Baseline full precision on CPU'
}

# F.3 QINT8 — Dynamic Quantization (torch.ao)

qint8_base_model = EmotionCNNDeepFC(
    num_classes=num_classes
)

qint8_base_model.load_state_dict(
    torch.load(
        'best_emotion_model.pth',
        map_location='cpu'
    )
)

qint8_base_model.eval()
qint8_model = torch.ao.quantization.quantize_dynamic(
    qint8_base_model,
    {nn.Linear},
    dtype=torch.qint8
)

qint8_model.eval()
models_to_test['qint8'] = {
    'model': qint8_model,

    'device': 'cpu',

    'size_kb': get_object_size_kb(qint8_model),

    'note': 'Dynamic INT8 quantization using torch.ao.quantization'
}

# F.4 FLOAT16 — Half Precision
# FP16 lebih efisien di GPU; di CPU bisa lambat untuk beberapa operasi
fp16_device = 'cuda' if torch.cuda.is_available() else 'cpu'
fp16_model  = EmotionCNNDeepFC(num_classes=num_classes)
fp16_model.load_state_dict(torch.load('best_emotion_model.pth', map_location='cpu'))
fp16_model  = fp16_model.half().eval().to(fp16_device)

models_to_test['float16'] = {
    'model':   fp16_model,
    'device':  fp16_device,
    'size_kb': fp32_size * 0.5,   # estimasi: 16-bit = setengah 32-bit
    'note':    'Half precision (FP16). Optimal di GPU.'
}

# F.5 EXPERIMENTAL FP8
# EXPERIMENTAL FP8 TEST

try:
    fp8_model = EmotionCNNDeepFC(
        num_classes=num_classes
    )

    fp8_model.load_state_dict(
        torch.load(
            'best_emotion_model.pth',
            map_location='cpu'
        )
    )

    fp8_model = fp8_model.to('cuda')

    # convert parameter ke float8
    for param in fp8_model.parameters():
        param.data = param.data.to(torch.float8_e4m3fn)
    print("FP8 conversion success")

except Exception as e:
    print("FP8 conversion failed")
    print(e)

# TEST FP8 INFERENCE
try:
    dummy = torch.randn(
        1, 1, 48, 48,
        device='cuda'
    ).to(torch.float8_e4m3fn)
    output = fp8_model(dummy)
    print("FP8 inference success")
    print("Output shape:", output.shape)

except Exception as e:
    print("FP8 inference failed")
    print(e)

# F.5 SIMULATED LOW PRECISION VARIANTS
# FP8 / FP4 / QINT4 belum didukung native secara stabil
# pada PyTorch standar dan hardware umum.
#
# Oleh karena itu:
# - ukuran model disimulasikan berdasarkan rasio bit
# - accuracy dan latency masih menggunakan fallback FP32
# - digunakan untuk analisis potensi kompresi model

simulated_variants = {
    'float8_simulated': 8,
    'float4_simulated': 4,
    'qint4_simulated':  4,
}

for name, bits in simulated_variants.items():

    estimated_size = fp32_size * (bits / 32)

    models_to_test[name] = {
        'model':   fp32_model,
        'device':  'cuda',
        'size_kb': estimated_size,
        'note':    f'Simulated {bits}-bit — size estimation only'
    }

print('SIMULATED LOW PRECISION VARIANTS')

for k, v in models_to_test.items():
    print(f'''
Variant : {k}
Size KB : {v["size_kb"]:.2f}
Note    : {v["note"]}
''')

# F.6 ANALISIS LOW-BIT QUANTIZATION
print("LOW-BIT QUANTIZATION ANALYSIS")

print("""
Float8, Float4, dan QINT4 digunakan sebagai simulasi
low precision quantization untuk melihat potensi
pengurangan ukuran model pada deployment masa depan.

Semakin kecil precision:
- ukuran model semakin kecil
- kebutuhan memori semakin rendah
- potensi deployment embedded semakin baik

Namun:
- stabilitas numerik dapat menurun
- akurasi dapat berkurang
- hardware support masih terbatas
""")

# F.7 ESTIMASI KOMPRESI MODEL

baseline_size = fp32_size

print("ESTIMATED COMPRESSION RATIO")

for name in simulated_variants.keys():

    variant_size = models_to_test[name]['size_kb']

    compression_ratio = baseline_size / variant_size

    print(f'''
{name}

Original Size : {baseline_size:.2f} KB
Compressed    : {variant_size:.2f} KB
Compression   : {compression_ratio:.2f}x
''')

# ESTIMASI KOMPRESI MODEL
compression_labels = []
compression_values = []

for name in simulated_variants.keys():
    variant_size = models_to_test[name]['size_kb']

    ratio = baseline_size / variant_size

    compression_labels.append(name)
    compression_values.append(ratio)

plt.figure(figsize=(7,4))

plt.bar(compression_labels, compression_values)

plt.ylabel("Compression Ratio")
plt.title("Compression Ratio vs FP32")

plt.grid(axis='y', linestyle='--', alpha=0.4)

plt.show()

# F.8 VISUALISASI LOW-BIT MODEL SIZE

lowbit_names = list(simulated_variants.keys())

lowbit_sizes = [
    models_to_test[k]['size_kb']
    for k in lowbit_names
]

plt.figure(figsize=(8,5))

plt.bar(
    lowbit_names,
    lowbit_sizes,
    color=['orange', 'purple', 'red']
)

plt.title('Simulated Low-Bit Model Size')
plt.ylabel('Size (KB)')

plt.grid(axis='y', linestyle='--', alpha=0.4)

plt.show()

# F.9 POTENSI DEPLOYMENT LOW-BIT

deployment_notes = {
    'float8_simulated':
        'Potensi deployment lightweight GPU inference.',

    'float4_simulated':
        'Potensi ultra lightweight embedded AI.',

    'qint4_simulated':
        'Potensi deployment edge AI dan IoT device.'
}

print("LOW-BIT DEPLOYMENT POTENTIAL")

for k, v in deployment_notes.items():

    print(f'''
{k}
→ {v}
''')

"""<B> G. COMPARISON - ACCURACY, SIZE, LATENCY"""

# G.1 EVALUASI AKURASI SEMUA VARIANT
@torch.no_grad()
def evaluate_variant(model, loader, variant_device='cpu', use_half=False):
    model.eval()
    model = model.to(variant_device)
    correct, total = 0, 0
    for images, labels in loader:
        images = images.to(variant_device)
        labels = labels.to(variant_device)
        if use_half:
            images = images.half()
        outputs = model(images)
        _, preds = outputs.max(1)
        correct += preds.eq(labels).sum().item()
        total   += labels.size(0)
    return correct / total

accuracy_results = {}
for name, item in models_to_test.items():
    use_half = (name == 'float16')
    try:
        acc = evaluate_variant(item['model'], val_loader,
                               variant_device=item['device'], use_half=use_half)
    except Exception as e:
        print(f'{name} error saat evaluasi: {e}')
        acc = None
    accuracy_results[name] = acc
    print(f'{name:<22} accuracy: {acc}')

# G.2 LATENCY / KECEPATAN INFERENSI
@torch.no_grad()
def measure_latency(model, variant_device='cuda', use_half=False,
                    n_warmup=20, n_runs=100):
    model.eval()
    model  = model.to(variant_device)
    dummy  = torch.randn(1, 1, 48, 48).to(variant_device)
    if use_half:
        dummy = dummy.half()
    # Warmup
    for _ in range(n_warmup):
        _ = model(dummy)
    if variant_device == 'cuda':
        torch.cuda.synchronize()
    # Timing
    start = time.perf_counter()
    for _ in range(n_runs):
        _ = model(dummy)
    if variant_device == 'cuda':
        torch.cuda.synchronize()
    end = time.perf_counter()
    return ((end - start) / n_runs) * 1000   # ms

latency_results = {}
for name, item in models_to_test.items():
    use_half = (name == 'float16')
    try:
        lat = measure_latency(item['model'], variant_device=item['device'],
                              use_half=use_half)
    except Exception as e:
        print(f'{name} error saat latency test: {e}')
        lat = None
    latency_results[name] = lat
    print(f'{name:<22} latency: {lat:.4f} ms' if lat else f'{name} latency: None')

print("""
Catatan:
Latency antar varian tidak sepenuhnya apple-to-apple
karena FP32 dan FP16 diuji pada GPU,
sedangkan QINT8 diuji pada CPU.

Oleh karena itu latency digunakan
sebagai indikasi deployment scenario,
bukan perbandingan hardware identik.
""")

# G.3 TABEL PERBANDINGAN FINAL
baseline_acc = accuracy_results['fp32']
rows = []
for name, item in models_to_test.items():
    acc = accuracy_results[name]
    latency = latency_results[name]
    size = item['size_kb']

    acc_drop = (
        baseline_acc - acc
        if acc is not None and baseline_acc is not None
        else None
    )

    rows.append({
        'Model Variant': name,
        'Type': (
            'Simulated'
            if 'simulated' in name
            else 'Real'
        ),
        'Size (KB)': round(size, 2),
        'Val Accuracy': (
            round(acc, 4)
            if acc is not None
            else None
        ),
        'Accuracy Drop vs FP32': (
            round(acc_drop, 6)
            if acc_drop is not None
            else None
        ),
        'Latency ms/image': (
            round(latency, 4)
            if latency is not None
            else None
        ),
        'Device': item['device'],
        'Note': item['note']
    })

result_df = pd.DataFrame(rows)

# Pisahkan real vs simulated
real_df = result_df[
    result_df['Type'] == 'Real'
].copy()
sim_df = result_df[
    result_df['Type'] == 'Simulated'
].copy()

# Sorting
real_df = real_df.sort_values(
    by=['Val Accuracy', 'Latency ms/image'],
    ascending=[False, True]
).reset_index(drop=True)
sim_df = sim_df.sort_values(
    by=['Size (KB)'],
    ascending=[True]
).reset_index(drop=True)

# Gabungkan kembali
result_df = pd.concat(
    [real_df, sim_df],
    ignore_index=True
)

print("=" * 90)
print("FINAL MODEL COMPARISON")
print("=" * 90)

print(result_df.to_string(index=False))

print("""
Catatan:
- FP32 dan FP16 diuji pada GPU
- QINT8 diuji pada CPU
- FLOAT8, FLOAT4, dan QINT4 masih simulasi
- Latency digunakan sebagai indikasi deployment
""")

result_df

# G.4 VISUALISASI PERBANDINGAN

variants  = result_df['Model Variant'].tolist()
sizes     = result_df['Size (KB)'].tolist()
accuracies= result_df['Val Accuracy'].tolist()
latencies = result_df['Latency ms/image'].tolist()

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

axes[0].barh(variants, sizes, color='steelblue')
axes[0].set_title('Model Size (KB)'); axes[0].set_xlabel('KB')
axes[0].invert_xaxis()

axes[1].barh(variants, accuracies, color='seagreen')
axes[1].set_title('Val Accuracy'); axes[1].set_xlabel('Accuracy')
axes[1].set_xlim(0.80, 0.86)

axes[2].barh(variants, latencies, color='tomato')
axes[2].set_title('Inference Latency (ms/image)'); axes[2].set_xlabel('ms')

plt.tight_layout(); plt.show()

# G.5 CLASSIFICATION REPORT
@torch.no_grad()
def get_predictions(model, loader, eval_device=device):
    model.eval()
    all_preds, all_labels = [], []
    for images, labels in loader:
        images = images.to(eval_device)
        outputs = model(images)
        _, preds = outputs.max(1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.numpy())
    return np.array(all_labels), np.array(all_preds)

y_true, y_pred = get_predictions(model, val_loader)
class_names = train_dataset.classes

report = classification_report(y_true, y_pred, target_names=class_names, output_dict=True)


# PLOT CLASSIFICATION REPORT

metrics    = ['precision', 'recall', 'f1-score']
categories = class_names + ['macro avg', 'weighted avg']
x         = np.arange(len(metrics))
width     = 0.15
colors    = ['#378ADD', '#1D9E75', '#D85A30', '#7F77DD', '#BA7517']

fig, ax = plt.subplots(figsize=(10, 5))

for i, cat in enumerate(categories):
    vals = [report[cat][m] for m in metrics]
    bars = ax.bar(x + i * width, vals, width, label=cat, color=colors[i], alpha=0.85)
    for bar, val in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.003,
                f'{val:.2f}', ha='center', va='bottom', fontsize=8)

ax.set_ylim(0.75, 0.95)
ax.set_xticks(x + width * (len(categories) - 1) / 2)
ax.set_xticklabels(['Precision', 'Recall', 'F1-Score'], fontsize=11)
ax.set_ylabel('Score')
ax.set_title('Classification Report — Stress vs Non-Stress', fontsize=13)
ax.legend(loc='lower right', fontsize=9)
ax.axhline(y=report['accuracy'], color='gray', linestyle='--', linewidth=0.8, label='Overall Accuracy')
ax.grid(axis='y', linestyle='--', alpha=0.4)
plt.tight_layout()
plt.show()

# Tetap print tabel aslinya juga
print("\n Classification Report")
print(classification_report(y_true, y_pred, target_names=class_names))
print(f'\nOverall Accuracy: {report["accuracy"]:.4f}')

# G.6 ROC CURVE dan AUC
from sklearn.metrics import roc_curve, auc, roc_auc_score
@torch.no_grad()
def get_probs(model, loader, eval_device=device):
    model.eval()
    all_probs, all_labels = [], []
    for images, labels in loader:
        images = images.to(eval_device)
        outputs = model(images)
        probs = torch.softmax(outputs, dim=1)
        # Probabilitas kelas stress
        stress_probs = probs[:, 1].cpu().numpy()
        all_probs.extend(stress_probs)
        all_labels.extend(labels.numpy())
    return np.array(all_labels), np.array(all_probs)
y_true_auc, y_score = get_probs(model, val_loader)
roc_auc = roc_auc_score(y_true_auc, y_score)
fpr, tpr, thresholds = roc_curve(y_true_auc, y_score)
plt.figure(figsize=(7,6))

plt.plot(
    fpr,
    tpr,
    linewidth=3,
    label=f'ROC Curve (AUC = {roc_auc:.4f})'
)

plt.plot([0,1],[0,1], linestyle='--')

plt.xlabel('False Positive Rate', fontsize=12)
plt.ylabel('True Positive Rate', fontsize=12)

plt.title(
    f'ROC Curve — Stress vs Non-Stress\nAUC = {roc_auc:.4f}',
    fontsize=15,
    fontweight='bold'
)

plt.legend(fontsize=12)

plt.text(
    0.60,
    0.15,
    f'AUC = {roc_auc:.4f}',
    fontsize=16,
    fontweight='bold'
)

plt.grid(True, linestyle='--', alpha=0.4)

plt.tight_layout()
plt.show()

print(f'ROC-AUC Score: {roc_auc:.4f}')
print(f'ROC-AUC Score: {roc_auc:.4f}')

# G.6 ROC CURVE + AUC SCORE + DIAGONAL BASELINE
from sklearn.metrics import roc_curve, roc_auc_score, auc

@torch.no_grad()
def get_prediction_scores(model, loader, eval_device=device):
    model.eval()

    all_labels = []
    all_scores = []

    for images, labels in loader:
        images = images.to(eval_device)

        outputs = model(images)
        probs = torch.softmax(outputs, dim=1)

        # Ambil probabilitas kelas positif: stress
        stress_scores = probs[:, 1].detach().cpu().numpy()

        all_scores.extend(stress_scores)
        all_labels.extend(labels.numpy())

    return np.array(all_labels), np.array(all_scores)


# Ambil label asli dan probability score
y_true_auc, y_score = get_prediction_scores(model, val_loader, device)

# Hitung ROC dan AUC
fpr, tpr, thresholds = roc_curve(y_true_auc, y_score)
roc_auc = roc_auc_score(y_true_auc, y_score)

print(f"ROC-AUC Score: {roc_auc:.4f}")

# Visualisasi
# y_true = label asli, misalnya 1 = Stress, 0 = Non-Stress
# y_score = probabilitas/prediksi skor untuk kelas Stress

fpr, tpr, thresholds = roc_curve(y_true, y_score, pos_label=1)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8, 6))

plt.plot(fpr, tpr, linewidth=2, label=f"ROC Curve")
plt.plot([0, 1], [0, 1], linestyle="--", linewidth=1.5, label="Random Classifier")

plt.title(f"ROC Curve: Stress vs Non-Stress\nAUC = {roc_auc:.4f}", fontsize=14, fontweight="bold")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.grid(True, alpha=0.3)
plt.legend(loc="lower right")

plt.tight_layout()
plt.show()

# G.8 CONFUSION MATRIX HEATMAP
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

# G.9 TRADEOFF ANALYSIS
print("TRADEOFF ANALYSIS")

print("""
Semakin kecil precision model:
- ukuran model semakin kecil
- penggunaan memori lebih ringan
- latency inferensi lebih cepat

Namun:
- terdapat potensi penurunan akurasi
- stabilitas numerik dapat berkurang

Tradeoff ini penting dalam deployment realtime.
""")

# G.10 DEPLOYMENT RECOMMENDATION
print("DEPLOYMENT RECOMMENDATION")

print("""
FP32
- baseline full precision
- cocok untuk training dan evaluasi

FP16
- cocok untuk deployment GPU karena ukuran model lebih kecil
- accuracy setara dengan FP32
- latency pada eksperimen ini belum lebih cepat dari FP32 GPU

QINT8
- cocok untuk deployment CPU ringan
- ukuran model lebih kecil
- inferensi lebih efisien

FLOAT8 / FLOAT4 / QINT4
- masih berupa simulasi
- digunakan untuk eksperimen future low-bit deployment
""")

# G.11 LIMITATIONS
print("LIMITATIONS")

print("""
- FLOAT8, FLOAT4, dan QINT4 masih berupa simulasi.
- Native low-bit quantization belum digunakan.
- Quantization hanya diterapkan pada layer nn.Linear.
- Full CNN quantization belum dilakukan.
- Evaluasi masih menggunakan validation set.
""")

# G.12 FUTURE WORK

print("FUTURE WORK")

print("""
- Menggunakan test set terpisah agar evaluasi lebih objektif.
- Menggunakan pretrained model seperti MobileNetV2 atau ResNet18.
- Melakukan full CNN quantization pada seluruh layer convolution.
- Menggunakan Quantization-Aware Training (QAT).
- Benchmark latency pada hardware identik.
- Deployment menggunakan ONNX atau TensorRT.
- Menggunakan real native low-bit quantization jika hardware support tersedia.
""")

"""<b> H. CONCLUSION - PEMILIHAN MODEL TERBAIK"""

# I.1 FINAL CONCLUSION
print("FINAL CONCLUSION")

print("""
Model CNN berhasil digunakan untuk klasifikasi
stress dan non_stress menggunakan ekspresi wajah.

Model memperoleh validation accuracy sekitar 84.81%.

Pengecekan duplikat antara train dan validation dilakukan
untuk membantu mencegah data leakgae.

FP16 berhasil digunakan sebagai half-precision inference,
sedangkan QINT8 berhasil digunakan sebagai
dynamic quantization pada layer Linear.

FP16 memberikan ukuran model lebih kecil dengan akurasi setara FP32,
sehingga cocok untuk deployment GPU.
Pada pengujian ini, latency FP32 GPU masih lebih rendah dibanding FP16.
QINT8 lebih ringan untuk deployment CPU karena ukuran model lebih kecil
dan latency lebih rendah dibanding FP32 CPU.

Eksperimen FLOAT8, FLOAT4, dan QINT4
digunakan sebagai analisis low-bit quantization
untuk future deployment research.

Secara keseluruhan proyek menunjukkan tradeoff
antara accuracy, ukuran model, dan latency
dalam deployment sistem multimedia realtime.
""")

# H.2 PROJECT SUMMARY
summary = pd.DataFrame({
    'Aspect': [
        'Dataset',
        'Model',
        'Best Accuracy',
        'ROC-AUC',
        'Best GPU Variant',
        'Best CPU Variant',
        'Quantization',
        'Deployment',
        'Multimedia Integration'

    ],

    'Result': [
        'FER2013',
        'Custom CNN',
        '84.81%',
        '0.9264',
        'FP16',
        'QINT8',
        'FP16 / QINT8 / Low-bit Simulation',
        'Deployment-Oriented Analysis',
        'Dashboard + Webcam Concept'
    ]
})
summary

# H. SIMPULAN OTOMATIS
# Memilih model terbaik hanya dari real variants, bukan simulated variants

real_valid_df = result_df[
    result_df['Type'] == 'Real'
].dropna(subset=['Val Accuracy', 'Latency ms/image']).copy()

acc_threshold = baseline_acc - 0.02

candidate_df = real_valid_df[
    real_valid_df['Val Accuracy'] >= acc_threshold
].copy()

if len(candidate_df) == 0:
    candidate_df = real_valid_df.copy()

best = candidate_df.sort_values(
    by=['Latency ms/image', 'Val Accuracy'],
    ascending=[True, False]
).iloc[0]

print('SIMPULAN AKHIR')
print(f'Baseline FP32 Accuracy : {baseline_acc:.4f}')
print()
print('Model real terbaik berdasarkan accuracy threshold dan latency:')
print(f' Variant : {best["Model Variant"]}')
print(f' Accuracy : {best["Val Accuracy"]:.4f}')
print(f' Size : {best["Size (KB)"]:.2f} KB')
print(f' Latency : {best["Latency ms/image"]:.4f} ms/image')
print(f' Device : {best["Device"]}')
print()
print('Analisis:')
print('- Model simulated tidak dipilih sebagai model terbaik karena hanya estimasi ukuran.')
print('- FP32 GPU menjadi baseline dengan latency tercepat pada GPU di eksperimen ini.')
print('- FP16 cocok untuk deployment GPU ketika prioritasnya ukuran model lebih kecil.')
print('- QINT8 cocok untuk deployment CPU karena lebih kecil dan lebih cepat dibanding FP32 CPU.')